---
# tasks file for install puppet-agent on Linux

- name: Debian | Update apt cache
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Gentoo | Update emerge cache
  shell: emerge-webrsync
  changed_when: false
  when: ansible_os_family == "Gentoo"

- name: Linux | Install puppet-agent from Puppetlabs repository
  package:
    name: puppet-agent
    state: present
  when: install_from == "puppetlabs_repository"

- name: Linux | Install puppet-agent from os repository
  package:
    name: "{{ puppet_agent_package }}"
    state: present
  when: install_from == "os_repository"

- name: Linux | Puppet-agent service
  service:
    name: "{{ puppet_agent_service }}"
    state: started
    enabled: yes
