---
# add Puppetlabs repository in Fedora
- name: Fedora | Add Puppetlabs rpm key
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet'
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet-20250406'
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs'
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-reductive'

- name: Fedora | Add Puppetlabs repository
  yum_repository:
    name: puppet{{ puppet_version }}
    description: Puppet {{ puppet_version }} Repository fedora {{ ansible_distribution_major_version }} - $basearch
    baseurl: http://yum.puppetlabs.com/puppet{{ puppet_version }}/fedora/{{ ansible_distribution_major_version }}/$basearch
    gpgcheck: true
    gpgkey:
      - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet'
      - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet-20250406'
    enabled: true
    state: present

- name: Fedora | Add Puppetlabs source repository
  yum_repository:
    name: puppet{{ puppet_version }}-source
    description: Puppet {{ puppet_version }} Repository fedora {{ ansible_distribution_major_version }} - Source
    baseurl: http://yum.puppetlabs.com/puppet{{ puppet_version }}-nightly/fedora/{{ ansible_distribution_major_version }}/SRPMS
    gpgcheck: true
    gpgkey:
      - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet'
      - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet-20250406'
    enabled: true
    state: "{{ puppetlabs_repo_source }}"
