---
# add Puppetlabs repository in SLES
- name: Suse | Add Puppetlabs rpm key
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet'
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet-20250406'
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs'
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-reductive'

- name: Suse | Add Puppetlabs repository
  zypper:
    name: "https://yum.puppet.com/puppet{{ puppet_version }}-release-sles-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
