name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    name: ${{ matrix.image }} puppet ${{ matrix.puppet_version }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - centos:8
          - centos:7
          - centos:6
          - fedora:30
          - fedora:29
          - fedora:28
          - fedora:27
          - fedora:26
          - ubuntu:18.04
          - ubuntu:16.04
          - ubuntu:14.04
          - debian:10
          - debian:9
          - debian:8
          - oraclelinux:8
          - oraclelinux:7
          - oraclelinux:6
          - amazonlinux:2
          - amazonlinux:1
          - opensuse:leap
        puppet_version:
          - 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint molecule-docker docker

      - name: Test Ansible role
        run: molecule test
        env:
          image: ansible-${{ matrix.image }}
          puppet_version: ${{ matrix.puppet_version }}

      - name: Test Ansible role with check_mode enable
        run: molecule check
        env:
          image: ansible-${{ matrix.image }}
          puppet_version: ${{ matrix.puppet_version }}
